const eventData = [
    {
        id: 1,
        name: "Toxxyk Experience",
        date: "2025-08-15",
        time: "6:00 PM",
        location: "Saga Bay,Gisenyi",
        category: "Music",
        price: "25k RWF",
        image: "images/toxxyk experience.jpg",
        description: "Join us for an unforgettable evening of live music featuring top artists from around the world. Experience the magic of live performances under the stars with food trucks and vendors offering delicious cuisine from various cultures.",
        organizer: "Move Rwanda",
        capacity: "Unlimited",
        tags: ["outdoor", "live music", "festival", "food trucks"]
    },
    {
        id: 2,
        name: "Women in Tech Conference",
        date: "2025-07-22",
        time: "9:00 AM",
        location: "Convention Center, Kigali",
        category: "Technology",
        price: "Free",
        image: "images/women in tech.jpg",
        description: "Discover the latest trends in technology and innovation. Network with industry leaders and learn about cutting-edge developments in AI, blockchain, and emerging technologies that will shape our future.",
        organizer: "ALX",
        capacity: "50 people",
        tags: ["conference", "networking", "innovation", "AI", "blockchain"]
    },
    {
        id: 3,
        name: "Kigali Peace Marathon",
        date: "2025-09-10",
        time: "7:00 AM",
        location: "Amahoro Stadium, Kigali",
        category: "Sports",
        price: "8k RWF",
        image: "images/peace marathon.jpg",
        description: "Challenge yourself in our annual marathon championship. Whether you're a seasoned runner or a beginner, join thousands of participants in this exciting race through the beautiful streets of Chicago.",
        organizer: "Ministry of Sports",
        capacity: "-",
        tags: ["running", "fitness", "competition", "outdoor", "health"]
    },
    {
        id: 4,
        name: "Entrepreneurship Leadership Summit",
        date: "2025-07-28",
        time: "8:00 AM",
        location: "ALU, Bumbogo",
        category: "Business",
        price: "7K RWF, Free for ALU students",
        image: "images/Leadership summit.jpg",
        description: "Learn from successful entrepreneurs and business leaders. Gain insights into leadership, strategy, and building successful companies. Network with like-minded professionals and discover new opportunities.",
        organizer: "Miami Business Council",
        capacity: "50 people",
        tags: ["business", "leadership", "entrepreneurship", "networking", "strategy"]
    },
    {
        id: 5,
        name: "Karaoke night",
        date: "2025-07-30",
        time: "5:00 PM",
        location: "Bicu lounge, Kigali",
        category: "Music",
        price: "15k RWF",
        image: "images/bicu lounge.jpg",
        description: "Enjoy smooth music and  performances by renowned musicians in Kigali. Enjoy an evening of sophisticated music and karaoke performances in a beautiful outdoor setting.",
        organizer: "Lady Bicu",
        capacity: "80 people",
        tags: ["Karaoke", "outdoor", "music", "evening", "relaxing"]
    },
    {
        id: 6,
        name: "Digital Art Workshop",
        date: "2025-07-25",
        time: "10:00 AM",
        location: "Creative Studio, Kakiru",
        category: "Arts",
        price: "20k RWF",
        image: "images/digital art workshops.avif",
        description: "Learn digital art techniques from professional artists. This hands-on workshop covers digital painting, illustration, and design principles. All skill levels welcome.",
        organizer: "Creative Collective",
        capacity: "50 people",
        tags: ["digital art", "workshop", "painting", "illustration", "creative"]
    },
    {
        id: 7,
        name: "Fitness",
        date: "2025-08-20",
        time: "6:00 AM",
        location: "SOHO club, Kimihurura",
        category: "Sports",
        price: "30k RWF",
        image: "images/soho fitness.jpg",
        description: "Start your day with an energizing fitness bootcamp. Professional trainers will guide you through a full-body workout suitable for all fitness levels.",
        organizer: "SOHO Fitness Club",
        capacity: "200 people",
        tags: ["fitness", "bootcamp", "workout", "morning"]
    }
];